# Generated by Django 6.0 on 2025-12-27 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('camera_index', models.IntegerField(default=0, help_text='Camera index for cv2.VideoCapture (0 for default)')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='lecture',
            name='carried_from',
            field=models.ForeignKey(blank=True, help_text='Previous lecture from which attendance was carried forward', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carried_to', to='core.lecture'),
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='timetable',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='core.room'),
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('room', 'day_of_week', 'start_time')},
        ),
    ]
