# Generated by Django 6.0 on 2025-12-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_room_lecture_carried_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo_left',
            field=models.CharField(blank=True, help_text='Looking left photo path', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='photo_right',
            field=models.CharField(blank=True, help_text='Looking right photo path', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='photo_straight',
            field=models.CharField(blank=True, help_text='Front-facing photo path', max_length=255),
        ),
    ]
