# Generated by Django 6.0 on 2025-12-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_student_photo_left_student_photo_right_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='extra_date',
            field=models.DateField(blank=True, help_text='Specific date for non-recurring lectures', null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='is_recurring',
            field=models.BooleanField(default=True, help_text='False for extra/one-time lectures'),
        ),
    ]
