# Generated by Django 6.0 on 2025-12-28 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_timetable_extra_date_timetable_is_recurring'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelledLecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('cancelled_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.teacher')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellations', to='core.timetable')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('timetable', 'date')},
            },
        ),
    ]
