# Generated by Django 6.0 on 2025-12-29 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cancelledlecture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancelledlecture',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.teacher'),
        ),
        migrations.AlterField(
            model_name='cancelledlecture',
            name='date',
            field=models.DateField(help_text='The specific date this lecture is cancelled'),
        ),
    ]
